# Generated by Django 3.0.3 on 2020-02-27 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
